-- Create audits table
CREATE TABLE IF NOT EXISTS audits (
  id TEXT PRIMARY KEY,
  tools JSONB NOT NULL,
  total_savings DECIMAL(10,2) NOT NULL,
  annual_savings DECIMAL(10,2) NOT NULL,
  is_public BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_audits_id ON audits(id);
CREATE INDEX IF NOT EXISTS idx_audits_is_public ON audits(is_public);
CREATE INDEX IF NOT EXISTS idx_audits_created_at ON audits(created_at);

-- Enable RLS (Row Level Security)
ALTER TABLE audits ENABLE ROW LEVEL SECURITY;

-- Create policy for public access to public audits
CREATE POLICY "Public audits are viewable by everyone"
  ON audits FOR SELECT
  USING (is_public = true);

-- Create policy for insert access (anyone can create audits)
CREATE POLICY "Anyone can create audits"
  ON audits FOR INSERT
  WITH CHECK (true);

-- Create policy for update access (only audit owners can update)
CREATE POLICY "Audit owners can update their audits"
  ON audits FOR UPDATE
  USING (true);

-- Function to automatically update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger to automatically update updated_at
CREATE TRIGGER update_audits_updated_at
  BEFORE UPDATE ON audits
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Create leads table
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  company_name TEXT,
  role TEXT,
  audit_id TEXT NOT NULL,
  total_savings DECIMAL(10,2) NOT NULL,
  annual_savings DECIMAL(10,2) NOT NULL,
  tools_count INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for leads table
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads(email);
CREATE INDEX IF NOT EXISTS idx_leads_audit_id ON leads(audit_id);
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads(created_at);

-- Add unique constraint to prevent duplicate email submissions for same audit
CREATE UNIQUE INDEX IF NOT EXISTS idx_leads_email_audit ON leads(email, audit_id);

-- Enable RLS for leads table
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Create policy for insert access (anyone can submit leads)
CREATE POLICY "Anyone can submit leads"
  ON leads FOR INSERT
  WITH CHECK (true);

-- Create policy for select access (only service role can view leads)
CREATE POLICY "Service role can view all leads"
  ON leads FOR SELECT
  USING (auth.role() = 'service_role');
