import { NextRequest, NextResponse } from 'next/server';
import { AuditResult } from '@/lib/auditEngine';

interface SummaryRequest {
  results: AuditResult[];
  totalSavings: number;
  annualSavings: number;
}

const generateFallbackSummary = (data: SummaryRequest): string => {
  const toolsCount = data.results.length;
  const savingsMonthly = data.totalSavings.toFixed(0);
  const savingsAnnual = data.annualSavings.toFixed(0);
  const optimizationsCount = data.results.filter(r => r.savings > 0).length;
  
  return `Your AI spending analysis of ${toolsCount} tools reveals ${optimizationsCount} optimization opportunities. You can save $${savingsMonthly} monthly ($${savingsAnnual} annually) by switching to more cost-effective plans. The biggest savings come from right-sizing your team plans and exploring alternative tools. Implement these changes to optimize your AI budget without sacrificing productivity.`;
};

const generatePrompt = (data: SummaryRequest): string => {
  const toolsList = data.results.map(tool => 
    `${tool.name} (${tool.currentPlan} plan, ${tool.seats} seats, $${tool.currentSpend}/month): ${tool.recommendation} - Save $${tool.savings.toFixed(2)}/month`
  ).join('\n');

  return `As a financial advisor, analyze this AI spending audit and provide a professional, helpful summary in exactly 100 words:

Audit Results:
- Total tools: ${data.results.length}
- Monthly savings potential: $${data.totalSavings.toFixed(2)}
- Annual savings potential: $${data.annualSavings.toFixed(2)}

Tool Details:
${toolsList}

Requirements:
- Exactly 100 words
- Professional, helpful, slightly persuasive tone
- Focus on financial benefits and actionable insights
- Highlight key optimization opportunities
- End with encouragement to implement changes

Summary:`;
};

export async function POST(request: NextRequest) {
  try {
    const body: SummaryRequest = await request.json();
    
    if (!body.results || !Array.isArray(body.results)) {
      return NextResponse.json(
        { error: 'Invalid request body' },
        { status: 400 }
      );
    }

    // Generate fallback summary first
    const fallbackSummary = generateFallbackSummary(body);

    // Check if OpenAI API key is available
    const apiKey = process.env.OPENAI_API_KEY;
    
    if (!apiKey) {
      console.warn('OpenAI API key not found, using fallback summary');
      return NextResponse.json({
        summary: fallbackSummary,
        source: 'fallback'
      });
    }

    // Generate AI summary
    const prompt = generatePrompt(body);
    
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: 'gpt-3.5-turbo',
        messages: [
          {
            role: 'system',
            content: 'You are a financial advisor specializing in SaaS and AI tool optimization. Provide concise, actionable insights in exactly 100 words.'
          },
          {
            role: 'user',
            content: prompt
          }
        ],
        max_tokens: 150,
        temperature: 0.7,
      }),
    });

    if (!response.ok) {
      console.error('OpenAI API error:', response.status, response.statusText);
      return NextResponse.json({
        summary: fallbackSummary,
        source: 'fallback'
      });
    }

    const data = await response.json();
    const aiSummary = data.choices?.[0]?.message?.content?.trim();

    if (!aiSummary) {
      console.error('No summary generated by AI');
      return NextResponse.json({
        summary: fallbackSummary,
        source: 'fallback'
      });
    }

    // Ensure the summary is close to 100 words
    const wordCount = aiSummary.split(/\s+/).length;
    if (wordCount < 80 || wordCount > 120) {
      console.warn(`AI summary word count (${wordCount}) outside expected range, using fallback`);
      return NextResponse.json({
        summary: fallbackSummary,
        source: 'fallback'
      });
    }

    return NextResponse.json({
      summary: aiSummary,
      source: 'ai'
    });

  } catch (error) {
    console.error('Summary generation error:', error);
    
    // Generate fallback summary from request data if available
    try {
      const body: SummaryRequest = await request.clone().json();
      const fallbackSummary = generateFallbackSummary(body);
      
      return NextResponse.json({
        summary: fallbackSummary,
        source: 'fallback'
      });
    } catch {
      // Ultimate fallback if request parsing fails
      return NextResponse.json({
        summary: 'Your AI spending analysis reveals optimization opportunities that can significantly reduce your monthly costs. By implementing the recommended plan changes and exploring alternative tools, you can achieve substantial savings while maintaining productivity. Review the detailed recommendations and take action to optimize your AI tool budget.',
        source: 'fallback'
      });
    }
  }
}
